# src/main/resources/inventory.conf

akka {
    actor {
        # This turns on the clustering engine
        provider = "cluster"

            # Tell Akka to use Jackson to convert your Java objects to JSON for the network
            serialization-bindings {
"com.mani.akka.messages.InventoryCommand" = jackson-json
      "com.mani.akka.messages.InventoryCommand$CheckStockCommand" = jackson-json
      "com.mani.akka.messages.InventoryCommand$AddStockCommand" = jackson-json
      "com.mani.akka.messages.InventoryCommand$ReserveStockCommand" = jackson-json
      "com.mani.akka.messages.InventoryCommand$ConfirmOrderCommand" = jackson-json
      "com.mani.akka.messages.InventoryCommand$CancelOrderCommand" = jackson-json
      "com.mani.akka.messages.InventoryCommand$StockResponse" = jackson-json
      "com.mani.akka.messages.InventoryCommand$ReservationResponse" = jackson-json
      "com.mani.domain.Product" = jackson-json
      "com.mani.domain.Order" = jackson-json
      "com.mani.domain.InventoryState" = jackson-json
    }
  }

  remote {
    artery {
      enabled = on
      transport = tcp
      canonical.hostname = "127.0.0.1"
      # The port will be overridden when we start the app from the terminal
      canonical.port = 0
    }
  }

  cluster {
    # These are the "first contacts". When a new node starts, it looks for these IP/Ports to join the group
    seed-nodes = [
      "akka://InventoryCluster@127.0.0.1:2551",
      "akka://InventoryCluster@127.0.0.1:2552",
      "akka://InventoryCluster@127.0.0.1:2553"
    ]

    # Health check settings (how quickly it notices if a node dies)
    heartbeat-interval = 1s
    heartbeat-threshold = 10
  }
}